services:
  mysql:
    image: mysql:8.0.36
    container_name: mysql
    hostname: mysql
    ports:
      - "3306:3306"
    privileged: true
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      TZ: Asia/Shanghai
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:


# 查看 mysql 容器的日志，过滤 root 密码
# docker logs mysql | grep "GENERATED ROOT PASSWORD"

# 连接到 mysql 容器
# docker exec -it mysql mysql -u user -p

# 赋予 user 用户对 mydb 数据库（for prisma）的所有权限
# GRANT ALL PRIVILEGES ON mydb.* TO 'user'@'%' WITH GRANT OPTION;
# ALTER USER 'user'@'%' IDENTIFIED WITH mysql_native_password BY 'pass';

# FLUSH PRIVILEGES;
